### ISSUE TITLE
python 3.4+

### ISSUE THREAD

**Issue by wwood** [biocore/pyqi#268]
Hi,

Currently installation of pyqi through pip fails if the version of python is 3.4+, because the version is artificially restricted in `setup.py`
```
# Verify Python version
ver = '.'.join(map(str, [sys.version_info.major, sys.version_info.minor]))
if ver not in ['2.7', '3.3', '3.4']:
    sys.stderr.write("Only Python 2.7, 3.3, and 3.4 are supported.")
    sys.exit(1)
```
Would it be possible to remove this restriction? Are there any known issues for 3.4 or 3.5?

Thanks,
ben

**Comment by wwood** [comment]
Oh my mistake, I just came across https://github.com/biocore/pyqi/issues/263 where 3.4 support is now official and the setup.py has changed accordingly. Would you mind making a new release? Is 3.5 supported?

**Comment by wwood** [comment]
heh, 3.4 is even in my code copy/paste above.

**Comment by wasade** [comment]
@wwood, this repository is being phased out in favor of `click`. I'd be happy to merge a PR for a fix on this, but just know that we will not be actively adding in new features.

**Comment by wwood** [comment]
ok, maybe a disclaimer in the README would be helpful.

**Comment by gregcaporaso** [comment]
I agree. I'll do this now.

**Comment by gregcaporaso** [comment]
see #269

**Comment by wwood** [comment]
thanks.
